version: "3.8"
services:

  # Nginx reverse proxy with SSL
  # Handles incoming requests and forwards them through to 
  # other containers
  nginx:
    image: ghcr.io/weavc/weavc-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role!=manager"
    networks: 
      - web-overlay
      - metrics-overlay
    configs:
      - source: default.conf
        target: /sites/default.conf
      - source: logger.subdomain.conf
        target: /sites/logger.subdomain.conf
      - source: prometheus.subdomain.conf
        target: /sites/prometheus.subdomain.conf
<<<<<<< HEAD
      - source: grafana.subdomain.conf
        target: /sites/grafana.subdomain.conf
=======
<<<<<<< HEAD
      - source: grafana.subdomain.conf
        target: /sites/grafana.subdomain.conf
=======
>>>>>>> f56a2979152bb729aaa9332cd23d05cd47fd7e90
>>>>>>> 036fe951dcc82ed82b17d24362cf81cf1492d126
    secrets:
      - fullchain.pem
      - privkey.pem

  # Frontend web service
  web:
    image: ghcr.io/weavc/deploy-examples-web:latest
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role!=manager"
    networks: 
      - web-overlay
      - metrics-overlay
    configs:
      - source: shared_config.ini
        target: /shared_config.ini

  # Backend API web service
  logger:
    image: ghcr.io/weavc/deploy-examples-logger:latest
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role!=manager"
    networks: 
      - web-overlay
      - db-overlay
      - metrics-overlay
    configs:
      - source: shared_config.ini
        target: /shared_config.ini

  # Network tools
  # Tools to help test our docker network
  # IPerf, ping, tracert, curl etc
  network-tools:
    image: praqma/network-multitool:extra
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
    networks: 
      - web-overlay
      - metrics-overlay
      - db-overlay

<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
  prometheus:
    image: prom/prometheus
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
    networks: 
      - frontend
      - db-overlay
    volumes:
      - type: volume
        source: prometheus-data
        target: /data
    configs:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
>>>>>>> f56a2979152bb729aaa9332cd23d05cd47fd7e90

>>>>>>> 036fe951dcc82ed82b17d24362cf81cf1492d126
networks:
  web-overlay:
    driver: overlay
  db-overlay:
    external: true
    name: db-overlay
  metrics-overlay:
    external: true
    name: metrics-overlay

configs:
  shared_config.ini:
    file: ./configs/shared_config.ini
  default.conf:
    file: ./configs/sites/default.conf
  logger.subdomain.conf:
    file: ./configs/sites/logger.subdomain.conf
  prometheus.subdomain.conf:
    file: ./configs/sites/prometheus.subdomain.conf
<<<<<<< HEAD
  grafana.subdomain.conf:
    file: ./configs/sites/grafana.subdomain.conf
=======
<<<<<<< HEAD
  grafana.subdomain.conf:
    file: ./configs/sites/grafana.subdomain.conf
=======
  prometheus.yml:
    file: ./configs/prometheus.yml
>>>>>>> f56a2979152bb729aaa9332cd23d05cd47fd7e90
>>>>>>> 036fe951dcc82ed82b17d24362cf81cf1492d126

secrets:
  fullchain.pem:
    file: ./secrets/fullchain.pem
  privkey.pem:
    file: ./secrets/privkey.pem

volumes:
  prometheus-data: