version: "3.8"
services:

  # Nginx reverse proxy with SSL
  # Handles incoming requests and forwards them through to 
  # other containers
  nginx:
    image: ghcr.io/weavc/weavc-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
    networks: 
      - frontend
    configs:
      - source: default.conf
        target: /sites/default.conf
      - source: logger.subdomain.conf
        target: /sites/logger.subdomain.conf
    secrets:
      - fullchain.pem
      - privkey.pem

  # Frontend web service
  web:
    image: ghcr.io/weavc/deploy-examples-web:latest
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
    networks: 
      - frontend
    configs:
      - source: shared_config.ini
        target: /shared_config.ini

  # Backend API web service
  logger:
    image: ghcr.io/weavc/deploy-examples-logger:latest
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
    networks: 
      - frontend
      - db-overlay
    configs:
      - source: shared_config.ini
        target: /shared_config.ini

  # Network tools
  # Tools to help test our docker network
  # IPerf, ping, tracert, curl etc
  network-tools:
    image: praqma/network-multitool
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
    networks: 
      - frontend
      - db-overlay

  prometheus:
    image: prom/prometheus
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
    networks: 
      - frontend
      - db-overlay
    volumes:
      - type: volume
        source: prometheus-data
        target: /data
    configs:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml

      /etc/prometheus/prometheus.yml
networks:
  frontend:
    driver: overlay
  # internal database network from 'compose-databases.yml'
  db-overlay:
    external: true
    name: db-overlay

configs:
  shared_config.ini:
    file: ./configs/shared_config.ini
  default.conf:
    file: ./configs/sites/default.conf
  logger.subdomain.conf:
    file: ./configs/sites/logger.subdomain.conf
  prometheus.yml:
    file: ./configs/prometheus.yml

secrets:
  fullchain.pem:
    file: ./secrets/fullchain.pem
  privkey.pem:
    file: ./secrets/privkey.pem

volumes:
  prometheus-data: