version: "3"
services:

  # global python server to load balance over
  web:
    image: ghcr.io/weavc/deploy-examples-web:latest
    # bind to port 80 of host
    ports:
      - "80:5000"
    environment:
      LOGGER_ADDRESS: http://logger:5001
    # create a single replica on every node
    deploy:
      mode: replicated
      replicas: 10
    # attach to frontend overlay network
    # can communicate with log service, but not database
    networks: 
      - frontend
    configs:
      - shared_config.ini

  # database logging service
  logger:
    image: ghcr.io/weavc/deploy-examples-logger:latest
    ports:
      - "81:5000"
    # replicate over zones, zones could be datacenters or contries
    # however we decide to tag them
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
      # preferences:
      #   - spread: node.labels.zone
    # attach to frontend & database overlay network 
    # can communicated with db and web services
    networks: 
      - frontend
      - database
    configs:
      - shared_config.ini

  network-tools:
    image: praqma/network-multitool
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
    networks: 
      - frontend
      - database

  # single instance of database
  postgres:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deploy-examples
    deploy:
      # deploy 1 replica on node labeled database=yes
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.database==yes"
    # attach to database overlay network,
    # can communicated with log service
    networks: 
      - "frontend"
      - "database"
      
networks:
  frontend:
    driver: overlay
  database:
    driver: overlay

configs:
  shared_config.ini:
    file: ./shared_config.ini
          