version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "3.9"
        NODE_VERSION: lts/*

    volumes:
      - ..:/workspace:cached

    command: sleep infinity
    networks: 
    - service-dev

  postgres:
    container_name: postgres
    image: postgres:latest
    networks: 
    - service-dev
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deploy-examples

networks: 
    service-dev: