apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
    - name: web
      image: ghcr.io/weavc/deploy-examples-web:latest
      ports:
        - containerPort: 5000
      volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
  volumes:
  - name: config
    configMap:
      name: shared-config
      items:
        - key: shared_config.ini
          path: shared_config.ini