global:
  scrape_interval: 10s
  external_labels:
    monitor: 'local-monitor'

scrape_configs:

  - job_name: 'web-metrics'
    metrics_path: /metrics
    dns_sd_configs:
      - names:
        - tasks.web
        type: A
        port: 5000

  - job_name: 'logger-metrics'
    metrics_path: /metrics
    dns_sd_configs:
      - names:
        - tasks.logger
        type: A
        port: 5000

<<<<<<< HEAD
  - job_name: 'node'
    metrics_path: /metrics
    dns_sd_configs:
      - names:
        - tasks.node-exporter
        type: A
        port: 9100


  # Docker metrics
  # Host discovery isn't really a thing without external dns etc
  # so decided to go with node-exporter instead

=======
>>>>>>> f56a2979152bb729aaa9332cd23d05cd47fd7e90
  # {
  #   "metrics-addr" : "0.0.0.0:9323",
  #   "experimental" : true
  # }
<<<<<<< HEAD

  # - job_name: 'node-metrics'
  #   metrics_path: /metrics
      # static_configs:
      #   - targets: ['192.168.99.201:9323', '192.168.99.211:9323', '192.168.99.212:9323']
=======
  - job_name: 'node-metrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.99.201:9323', '192.168.99.211:9323', '192.168.99.212:9323']
>>>>>>> f56a2979152bb729aaa9332cd23d05cd47fd7e90
