
name: Docker Build and Push

on: 
  push:
    branches:
    - "master"
    release:
      types: [published]
    
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Publish Web
        uses: docker/build-push-action@v2
        with:
          context: ./services
          file: ./services/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: 
            - PYTHON_MODULE=web
          tags: ghcr.io/weavc/deploy-examples-web:latest

      - name: Build & Publish Logger
        uses: docker/build-push-action@v2
        with:
          context: ./services
          file: ./services/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: 
            - PYTHON_MODULE=logger
          tags: ghcr.io/weavc/deploy-examples-logger:latest